version: 1
labels:
- label: "work in progress"
  title: ".*(?i)wip.*"
- label: "feature"
  title: ".*(?i)feat.*"
- label: "hot fix"
  title: ".*(?i)hot fix.*"
- label: "fix"
  title: ".*Fix.*"
- label: "enhancement"
  title: ".*(?i)enhancement.*"
- label: "refactor"
  title: ".*(?i)refactor.*"
- label: "PoC"
  title: ".*(?i)poc.*"
- label: "map"
  title: ".*(?i)map.*"
- label: "issue"
  title: ".*(?i)issue.*"
- label: "user"
  title: ".*(?i)user.*"
- label: "workflow"
  title: ".*(?i)workflow.*"
- label: "asset"
  title: ".*(?i)asset.*"
- label: "test"
  title: ".*Test.*"
