name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
  - title: ":recycle: Enhancements"
    labels:
      - "enhancement"
      - "refactor"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "hotfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "ci"
      - "chore"
      - "build"
  - title: "📝 Documentation"
    labels:
      - "documentations"
change-template: "- $TITLE #$NUMBER"
exclude-labels:
  - "skip-changelog"
template: |
  $CHANGES
