name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        # When skipIfReleaseExists is enabled the action will be skipped if a non-draft release already exists for the provided tag.
        skipIfReleaseExists: true