name: LabelMerge Conflicts

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conflicts-checker:
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Check merge conflicts
        uses: Marr11317/ConflictAdviser@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conflict_label: 'merge conflicts'
          comment: '😅 Merge conflicts detected'
